package com.parasoft.wsdl.calculator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * instance of class
 * 			webtool.soap.examples.calculator.Calculator
 *
 * This class was generated by Apache CXF 3.3.0
 * 2022-10-17T22:03:03.342+05:30
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "Calculator",
                  wsdlLocation = "file:/D:/Java%20Projects/soap-consumer-in-rest/src/main/resources/wsdl/calculator.wsdl",
                  targetNamespace = "http://www.parasoft.com/wsdl/calculator/")
public class Calculator extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.parasoft.com/wsdl/calculator/", "Calculator");
    public final static QName ICalculator = new QName("http://www.parasoft.com/wsdl/calculator/", "ICalculator");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Java%20Projects/soap-consumer-in-rest/src/main/resources/wsdl/calculator.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Calculator.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Java%20Projects/soap-consumer-in-rest/src/main/resources/wsdl/calculator.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Calculator(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Calculator(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Calculator() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Calculator(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Calculator(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Calculator(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ICalculator
     */
    @WebEndpoint(name = "ICalculator")
    public ICalculator getICalculator() {
        return super.getPort(ICalculator, ICalculator.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICalculator
     */
    @WebEndpoint(name = "ICalculator")
    public ICalculator getICalculator(WebServiceFeature... features) {
        return super.getPort(ICalculator, ICalculator.class, features);
    }

}
